cursor            #adc6ff
cursor_text_color #102f60

foreground            #e2e2e9
background            #0c0e13
selection_foreground  #293041
selection_background  #bfc6dc
url_color             #bfc6dc

#: black 000000 767676
color0  #111318
color8  #33353a
#: red cc0403 f2201f
color1  #000000
color9  #2f2f2f
#: green 19cb00 23fd00
color2  #bfc6dc
color10 #dbe2f9
#: yellow cecb00 fffd00
color3  #debcdf
color11 #fbd7fc
#: blue 0d73cc 1a8fff
color4  #2b4678
color12 #adc6ff
#: magenta cb1ed1 fd28ff
color5  #3f4759
color13 #bfc6dc
#: cyan 0dcdcd 14ffff
color6  #583e5b
color14 #debcdf
#: white dddddd ffffff
color7  #c4c6d0
color15 #e2e2e9

mark1_foreground #001a41
mark1_background #d8e2ff
mark2_foreground #141b2c
mark2_background #dbe2f9
mark3_foreground #29132d
mark3_background #fbd7fc

active_tab_foreground #102f60
active_tab_background #adc6ff
inactive_tab_foreground #d8e2ff
inactive_tab_background #2b4678

active_border_color #adc6ff
inactive_border_color #102f60
# bell_border_color #ff5a00