"$schema" = 'https://starship.rs/config-schema.json'

format = """
[\ue0b6](fg:color_bg0)\
$os\
$username\
[](bg:color_bg1 fg:color_bg0)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_status\
[](fg:color_bg2 bg:color_bg3)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg3 bg:color_bg4)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg4 bg:color_bg5)\
$time\
[](fg:color_bg5)\
$line_break$character"""

palette = 'matugen'

[palettes.matugen]
color_success   = '#c2c1ff'
color_error     = '#ffb4ab'
color_bg0       = '#c2c1ff'
color_fg0       = '#2b2a60'
color_bg1       = '#c6c4dd'
color_fg1       = '#2f2f42'
color_bg2       = '#eab9d2'
color_fg2       = '#472639'
color_bg3       = '#35343a'
color_fg3       = '#e5e1e9'
color_bg4       = '#201f25'
color_fg4       = '#e5e1e9'
color_bg5       = '#1b1b21'
color_fg5       = '#e5e1e9'

[os]
disabled = false
style = "bg:color_bg0 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Arch = "󰣇"
Artix = "󰣇"
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_fg0"
style_root = "bg:color_bg0 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol $branch ](fg:color_fg2 bg:color_bg2)]($style)'

[git_status]
style = "bg:color_bg2"
format = '[[($all_status$ahead_behind )](fg:color_fg2 bg:color_bg2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[bun]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[c]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[cpp]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[rust]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[python]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $context) ](fg:color_fg4 bg:color_bg4)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg5"
format = '[[  $time ](fg:color_fg5 bg:color_bg5)]($style)'

[line_break]
disabled = false

[character]
success_symbol = "[ ]( fg:color_success)"
error_symbol = "[ ]( fg:color_error)"
