-- This file is auto-generated by matugen, changes need to be made in the template file in .config/matugen/templates or will be overridden on changing the theme / wallpaper
local Colors = {}

Colors.background = "#111418"
Colors.on_background = "#e1e2e8"
Colors.primary = "#a1cafd"
Colors.on_primary = "#003259"
Colors.secondary = "#bbc7db"
Colors.on_secondary = "#253140"
Colors.error = "#ffb4ab"
Colors.on_error = "#690005"

return Colors
