-- This file is auto-generated by matugen, changes need to be made in the template file in .config/matugen/templates or will be overridden on changing the theme / wallpaper
local Colors = {}

Colors.background = "#1a1111"
Colors.on_background = "#f1dedd"
Colors.primary = "#ffb3ae"
Colors.on_primary = "#571d1c"
Colors.secondary = "#e7bdb9"
Colors.on_secondary = "#442928"
Colors.error = "#ffb4ab"
Colors.on_error = "#690005"

return Colors
