-- Auto-generated by matugen — do not edit
local Colors = {}

Colors.background = "#1a1111"
Colors.foreground = "#f0dede"
Colors.cursor     = "#ffb3b5"
Colors.color0     = "#140c0c"
Colors.color1     = "#ffb4ab"
Colors.color2     = "#e6bdbd"
Colors.color3     = "#e6c18d"
Colors.color4     = "#ffb3b5"
Colors.color5     = "#5d3f40"
Colors.color6     = "#5c421a"
Colors.color7     = "#d7c1c1"
Colors.color8     = "#322828"
Colors.color9     = "#ffdad6"
Colors.color10    = "#ffdada"
Colors.color11    = "#ffddb1"
Colors.color12    = "#733337"
Colors.color13    = "#e6bdbd"
Colors.color14    = "#e6c18d"
Colors.color15    = "#f0dede"

return Colors
