pragma Singleton
import QtQuick

// Auto-generated by matugen — do not edit
QtObject {
    readonly property color background:     "{{ colors.surface.default.hex }}"
    readonly property color foreground:     "{{ colors.on_surface.default.hex }}"
    readonly property color color0:         "{{ colors.surface_container_lowest.default.hex }}"
    readonly property color color1:         "{{ colors.error.default.hex }}"
    readonly property color color2:         "{{ colors.secondary.default.hex }}"
    readonly property color color3:         "{{ colors.tertiary.default.hex }}"
    readonly property color color4:         "{{ colors.primary.default.hex }}"
    readonly property color color5:         "{{ colors.secondary_container.default.hex }}"
    readonly property color color6:         "{{ colors.tertiary_container.default.hex }}"
    readonly property color color7:         "{{ colors.on_surface_variant.default.hex }}"
    readonly property color color8:         "{{ colors.surface_container_high.default.hex }}"
    readonly property color accent:         "{{ colors.primary.default.hex }}"
    readonly property color dim:            "{{ colors.surface_container_high.default.hex }}"
}
