-- Auto-generated by matugen — do not edit
local Colors = {}

Colors.background = "{{ colors.surface.dark.hex }}"
Colors.on_background = "{{ colors.on_surface.dark.hex }}"
Colors.primary = "{{ colors.primary.dark.hex }}"
Colors.on_primary = "{{ colors.on_primary.dark.hex }}"
Colors.secondary = "{{ colors.secondary.dark.hex }}"
Colors.on_secondary = "{{ colors.on_secondary.dark.hex }}"
Colors.error = "{{ colors.error.dark.hex }}"
Colors.on_error = "{{ colors.on_error.dark.hex }}"

return Colors
