-- This file is auto-generated by matugen, changes need to be made in the template file in .config/matugen/templates or will be overridden on changing the theme / wallpaper
local Colors = {}

Colors.background = "{{ colors.surface.dark.hex }}"
Colors.on_background = "{{ colors.on_surface.dark.hex }}"
Colors.primary = "{{ colors.primary.dark.hex }}"
Colors.on_primary = "{{ colors.on_primary.dark.hex }}"
Colors.secondary = "{{ colors.secondary.dark.hex }}"
Colors.on_secondary = "{{ colors.on_secondary.dark.hex }}"
Colors.error = "{{ colors.error.dark.hex }}"
Colors.on_error = "{{ colors.on_error.dark.hex }}"

return Colors
