-- Auto-generated by matugen — do not edit
local Colors = {}

Colors.background = "{{ colors.surface.default.hex }}"
Colors.foreground = "{{ colors.on_surface.default.hex }}"
Colors.cursor     = "{{ colors.primary.default.hex }}"
Colors.color0     = "{{ colors.surface_container_lowest.default.hex }}"
Colors.color1     = "{{ colors.error.default.hex }}"
Colors.color2     = "{{ colors.secondary.default.hex }}"
Colors.color3     = "{{ colors.tertiary.default.hex }}"
Colors.color4     = "{{ colors.primary.default.hex }}"
Colors.color5     = "{{ colors.secondary_container.default.hex }}"
Colors.color6     = "{{ colors.tertiary_container.default.hex }}"
Colors.color7     = "{{ colors.on_surface_variant.default.hex }}"
Colors.color8     = "{{ colors.surface_container_high.default.hex }}"
Colors.color9     = "{{ colors.on_error_container.default.hex }}"
Colors.color10    = "{{ colors.on_secondary_container.default.hex }}"
Colors.color11    = "{{ colors.on_tertiary_container.default.hex }}"
Colors.color12    = "{{ colors.primary_container.default.hex }}"
Colors.color13    = "{{ colors.secondary.default.hex }}"
Colors.color14    = "{{ colors.tertiary.default.hex }}"
Colors.color15    = "{{ colors.on_surface.default.hex }}"

return Colors
